name: colcom

services:
  db:
    image: postgres:16.4-alpine3.20
    environment: &env
      POSTGRES_DB: colcom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPORT: 5433
      TZ: America/Recife
    network_mode: host
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      args:
        TZ: America/Recife
    environment:
      <<: *env
      PORT: 3000
      DB_PATH: /app/gitDB
      NODE_ENV: production
    depends_on:
      - db
    network_mode: host
    restart: always
    volumes:
      - git_data:/app/gitDB

  frontend_nginx:
    build:
      context: ./frontend
      args:
        VITE_API_ADDRESS: http://localhost/api
    environment:
      TZ: America/Recife
    volumes:
      # - ./nginx/nginx-https.conf:/etc/nginx/nginx.conf:ro    # Uncomment for using https instead of http
      - ./nginx/nginx-http.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
    network_mode: host
    restart: always

volumes:
  postgres_data:
  git_data: