name: colcom

services:
  db:
    image: postgres:16.4-alpine3.20
    environment: &env
      POSTGRES_DB: colcom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPORT: 5433
      TZ: America/Recife
    network_mode: host
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      args:
        TZ: America/Recife
    environment:
      <<: *env
      PORT: 3000
      DB_PATH: /app/gitDB
      NODE_ENV: production
    depends_on:
      - db
    network_mode: host
    restart: always
    volumes:
      - git_data:/app/gitDB

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_ADDRESS: http://localhost/api
    volumes:
      - frontend_build:/app/dist

  nginx:
    image: nginx:1.27.1-alpine3.20
    container_name: nginx
    network_mode: host
    volumes:
      - frontend_build:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  postgres_data:
  git_data:
  frontend_build: # This volume needs to be cleared so changes can take effect
