name: colcom

services:
  db:
    image: postgres:16.4-alpine3.20
    environment: &env
      POSTGRES_DB: colcom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: &timezone America/Recife
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      args:
        TZ: *timezone
    environment:
      <<: *env
      PORT: 3000
      POSTGRES_HOST: db
      DB_PATH: /app/gitDB
      NODE_ENV: production
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - git_data:/app/gitDB

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_ADDRESS: http://localhost/api
    volumes:
      - frontend_build:/app/dist

  nginx:
    image: nginx:1.27.1-alpine3.20
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - frontend_build:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  postgres_data:
  git_data:
  frontend_build:
